// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.en');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Add Comment";
Blockly.Msg.CANNOT_DELETE_VARIABLE_PROCEDURE = "Can't delete the variable '%1' because it's part of the definition of the function '%2'";
Blockly.Msg.CHANGE_VALUE_TITLE = "Change value:";
Blockly.Msg.CLEAN_UP = "Clean up Blocks";
Blockly.Msg.COLLAPSE_ALL = "Collapse Blocks";
Blockly.Msg.COLLAPSE_BLOCK = "Collapse Block";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "colour 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "colour 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";
Blockly.Msg.COLOUR_BLEND_RATIO = "ratio";
Blockly.Msg.COLOUR_BLEND_TITLE = "blend";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Blends two colours together with a given ratio (0.0 - 1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Choose a colour from the palette.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";
Blockly.Msg.COLOUR_RANDOM_TITLE = "random colour";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Choose a colour at random.";
Blockly.Msg.COLOUR_RGB_BLUE = "blue";
Blockly.Msg.COLOUR_RGB_GREEN = "green";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";
Blockly.Msg.COLOUR_RGB_RED = "red";
Blockly.Msg.COLOUR_RGB_TITLE = "colour with";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Create a colour with the specified amount of red, green, and blue. All values must be between 0 and 100.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "break out of loop";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "continue with next iteration of loop";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Break out of the containing loop.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Skip the rest of this loop, and continue with the next iteration.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Warning: This block may only be used within a loop.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";
Blockly.Msg.CONTROLS_FOREACH_TITLE = "for each item %1 in list %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "For each item in a list, set the variable '%1' to the item, and then do some statements.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";
Blockly.Msg.CONTROLS_FOR_TITLE = "count with %1 from %2 to %3 by %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Have the variable '%1' take on the values from the start number to the end number, counting by the specified interval, and do the specified blocks.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Add a condition to the if block.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Add a final, catch-all condition to the if block.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Add, remove, or reorder sections to reconfigure this if block.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "else";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "else if";
Blockly.Msg.CONTROLS_IF_MSG_IF = "if";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "If a value is true, then do some statements.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "If a value is true, then do the first block of statements. Otherwise, do the second block of statements.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "If the first value is true, then do the first block of statements. Otherwise, if the second value is true, do the second block of statements.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "If the first value is true, then do the first block of statements. Otherwise, if the second value is true, do the second block of statements. If none of the values are true, do the last block of statements.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "do";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "repeat %1 times";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Do some statements several times.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "repeat until";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "repeat while";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "While a value is false, then do some statements.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "While a value is true, then do some statements.";
Blockly.Msg.DELETE_ALL_BLOCKS = "Delete all %1 blocks?";
Blockly.Msg.DELETE_BLOCK = "Delete Block";
Blockly.Msg.DELETE_VARIABLE = "Delete the '%1' variable";
Blockly.Msg.DELETE_VARIABLE_CONFIRMATION = "Delete %1 uses of the '%2' variable?";
Blockly.Msg.DELETE_X_BLOCKS = "Delete %1 Blocks";
Blockly.Msg.DISABLE_BLOCK = "Disable Block";
Blockly.Msg.DUPLICATE_BLOCK = "Duplicate";
Blockly.Msg.ENABLE_BLOCK = "Enable Block";
Blockly.Msg.EXPAND_ALL = "Expand Blocks";
Blockly.Msg.EXPAND_BLOCK = "Expand Block";
Blockly.Msg.EXTERNAL_INPUTS = "External Inputs";
Blockly.Msg.HELP = "Help";
Blockly.Msg.INLINE_INPUTS = "Inline Inputs";
Blockly.Msg.IOS_CANCEL = "Cancel";
Blockly.Msg.IOS_ERROR = "Error";
Blockly.Msg.IOS_OK = "OK";
Blockly.Msg.IOS_PROCEDURES_ADD_INPUT = "+ Add Input";
Blockly.Msg.IOS_PROCEDURES_ALLOW_STATEMENTS = "Allow statements";
Blockly.Msg.IOS_PROCEDURES_DUPLICATE_INPUTS_ERROR = "This function has duplicate inputs.";
Blockly.Msg.IOS_PROCEDURES_INPUTS = "INPUTS";
Blockly.Msg.IOS_VARIABLES_ADD_BUTTON = "Add";
Blockly.Msg.IOS_VARIABLES_ADD_VARIABLE = "+ Add Variable";
Blockly.Msg.IOS_VARIABLES_DELETE_BUTTON = "Delete";
Blockly.Msg.IOS_VARIABLES_EMPTY_NAME_ERROR = "You can't use an empty variable name.";
Blockly.Msg.IOS_VARIABLES_RENAME_BUTTON = "Rename";
Blockly.Msg.IOS_VARIABLES_VARIABLE_NAME = "Variable name";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "create empty list";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Returns a list, of length 0, containing no data records";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "list";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Add, remove, or reorder sections to reconfigure this list block.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "create list with";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Add an item to the list.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Create a list with any number of items.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "first";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# from end";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "get";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "get and remove";
Blockly.Msg.LISTS_GET_INDEX_LAST = "last";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "random";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "remove";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Returns the first item in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM = "Returns the item at the specified position in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Returns the last item in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Returns a random item in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Removes and returns the first item in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM = "Removes and returns the item at the specified position in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Removes and returns the last item in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Removes and returns a random item in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Removes the first item in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM = "Removes the item at the specified position in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Removes the last item in a list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Removes a random item in a list.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "to # from end";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "to #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "to last";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "get sub-list from first";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "get sub-list from # from end";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "get sub-list from #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Creates a copy of the specified portion of a list.";
Blockly.Msg.LISTS_INDEX_FROM_END_TOOLTIP = "%1 is the last item.";
Blockly.Msg.LISTS_INDEX_FROM_START_TOOLTIP = "%1 is the first item.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "find first occurrence of item";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";
Blockly.Msg.LISTS_INDEX_OF_LAST = "find last occurrence of item";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Returns the index of the first/last occurrence of the item in the list. Returns %1 if item is not found.";
Blockly.Msg.LISTS_INLIST = "in list";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 is empty";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Returns true if the list is empty.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";
Blockly.Msg.LISTS_LENGTH_TITLE = "length of %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Returns the length of a list.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_REPEAT_TITLE = "create list with item %1 repeated %2 times";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Creates a list consisting of the given value repeated the specified number of times.";
Blockly.Msg.LISTS_REVERSE_HELPURL = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";
Blockly.Msg.LISTS_REVERSE_MESSAGE0 = "reverse %1";
Blockly.Msg.LISTS_REVERSE_TOOLTIP = "Reverse a copy of a list.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "as";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "insert at";
Blockly.Msg.LISTS_SET_INDEX_SET = "set";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Inserts the item at the start of a list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM = "Inserts the item at the specified position in a list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Append the item to the end of a list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Inserts the item randomly in a list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Sets the first item in a list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM = "Sets the item at the specified position in a list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Sets the last item in a list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Sets a random item in a list.";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "ascending";
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "descending";
Blockly.Msg.LISTS_SORT_TITLE = "sort %1 %2 %3";
Blockly.Msg.LISTS_SORT_TOOLTIP = "Sort a copy of a list.";
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "alphabetic, ignore case";
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "numeric";
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "alphabetic";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "make list from text";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "make text from list";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Join a list of texts into one text, separated by a delimiter.";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Split text into a list of texts, breaking at each delimiter.";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "with delimiter";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "false";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Returns either true or false.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "true";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Return true if both inputs equal each other.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Return true if the first input is greater than the second input.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Return true if the first input is greater than or equal to the second input.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Return true if the first input is smaller than the second input.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Return true if the first input is smaller than or equal to the second input.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Return true if both inputs are not equal to each other.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg.LOGIC_NEGATE_TITLE = "not %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Returns true if the input is false. Returns false if the input is true.";
Blockly.Msg.LOGIC_NULL = "null";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Returns null.";
Blockly.Msg.LOGIC_OPERATION_AND = "and";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";
Blockly.Msg.LOGIC_OPERATION_OR = "or";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Return true if both inputs are true.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Return true if at least one of the inputs is true.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "if false";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "if true";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Check the condition in 'test'. If the condition is true, returns the 'if true' value; otherwise returns the 'if false' value.";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Return the sum of the two numbers.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Return the quotient of the two numbers.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Return the difference of the two numbers.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Return the product of the two numbers.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Return the first number raised to the power of the second number.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_TITLE = "change %1 by %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Add a number to variable '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Return one of the common constants: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_(graphics)";
Blockly.Msg.MATH_CONSTRAIN_TITLE = "constrain %1 low %2 high %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Constrain a number to be between the specified limits (inclusive).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
/// {{optional}}\nmath - The symbol for the binary operation modulo.
Blockly.Msg.MATH_MODULO_SYMBOL = "%";
Blockly.Msg.MATH_BITAND_SYMBOL = "&";
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "is divisible by";
Blockly.Msg.MATH_IS_EVEN = "is even";
Blockly.Msg.MATH_IS_NEGATIVE = "is negative";
Blockly.Msg.MATH_IS_ODD = "is odd";
Blockly.Msg.MATH_IS_POSITIVE = "is positive";
Blockly.Msg.MATH_IS_PRIME = "is prime";
Blockly.Msg.MATH_IS_TOOLTIP = "Check if a number is an even, odd, prime, whole, positive, negative, or if it is divisible by certain number. Returns true or false.";
Blockly.Msg.MATH_IS_WHOLE = "is whole";
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_TITLE = "remainder of %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Return the remainder from dividing the two numbers.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "A number.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "average of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "max of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "median of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "min of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "modes of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "random item of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "standard deviation of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "sum of list";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Return the average (arithmetic mean) of the numeric values in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Return the largest number in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Return the median number in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Return the smallest number in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Return a list of the most common item(s) in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Return a random element from the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Return the standard deviation of the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Return the sum of all the numbers in the list.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "random fraction";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Return a random fraction between 0.0 (inclusive) and 1.0 (exclusive).";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "random integer from %1 to %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Return a random integer between the two specified limits, inclusive.";
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "round";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "round down";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "round up";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Round a number up or down.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolute";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "square root";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Return the absolute value of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Return e to the power of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Return the natural logarithm of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Return the base 10 logarithm of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Return the negation of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Return 10 to the power of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Return the square root of a number.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
Blockly.Msg.MATH_TRIG_ACOS = "acos";
Blockly.Msg.MATH_TRIG_ASIN = "asin";
Blockly.Msg.MATH_TRIG_ATAN = "atan";
Blockly.Msg.MATH_TRIG_COS = "cos";
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";
Blockly.Msg.MATH_TRIG_TAN = "tan";
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Return the arccosine of a number.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Return the arcsine of a number.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Return the arctangent of a number.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Return the cosine of a degree (not radian).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Return the sine of a degree (not radian).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Return the tangent of a degree (not radian).";
Blockly.Msg.NEW_VARIABLE = "Create variable...";
Blockly.Msg.NEW_VARIABLE_TITLE = "New variable name:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "with:";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Run the user-defined function '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Run the user-defined function '%1' and use its output.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "with:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Create '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Describe this function...";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "do something";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "to";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Creates a function with no output.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "return";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Creates a function with an output.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Warning: This function has duplicate parameters.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Highlight function definition";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "If a value is true, then return a second value.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Warning: This block may be used only within a function definition.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "input name:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Add an input to the function.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "inputs";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Add, remove, or reorder inputs to this function.";
Blockly.Msg.PROCEDURE_ALREADY_EXISTS = "A procedure named '%1' already exists.";
Blockly.Msg.REDO = "Redo";
Blockly.Msg.REMOVE_COMMENT = "Remove Comment";
Blockly.Msg.RENAME_VARIABLE = "Rename variable...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Rename all '%1' variables to:";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";
Blockly.Msg.TEXT_APPEND_TITLE = "to %1 append text %2";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Append some text to variable '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "to lower case";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "to Title Case";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "to UPPER CASE";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Return a copy of the text in a different case.";
Blockly.Msg.TEXT_CHARAT_FIRST = "get first letter";
Blockly.Msg.TEXT_CHARAT_FROM_END = "get letter # from end";
Blockly.Msg.TEXT_CHARAT_FROM_START = "get letter #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";
Blockly.Msg.TEXT_CHARAT_LAST = "get last letter";
Blockly.Msg.TEXT_CHARAT_RANDOM = "get random letter";
Blockly.Msg.TEXT_CHARAT_TAIL = "";
Blockly.Msg.TEXT_CHARAT_TITLE = "in text %1 %2";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Returns the letter at the specified position.";
Blockly.Msg.TEXT_COUNT_HELPURL = "https://github.com/google/blockly/wiki/Text#counting-substrings";
Blockly.Msg.TEXT_COUNT_MESSAGE0 = "count %1 in %2";
Blockly.Msg.TEXT_COUNT_TOOLTIP = "Count how many times some text occurs within some other text.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Add an item to the text.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "join";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Add, remove, or reorder sections to reconfigure this text block.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "to letter # from end";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "to letter #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "to last letter";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "in text";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "get substring from first letter";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "get substring from letter # from end";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "get substring from letter #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Returns a specified portion of the text.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "find first occurrence of text";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "find last occurrence of text";
Blockly.Msg.TEXT_INDEXOF_TITLE = "in text %1 %2 %3";
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Returns the index of the first/last occurrence of the first text in the second text. Returns %1 if text is not found.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 is empty";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Returns true if the provided text is empty.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "create text with";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Create a piece of text by joining together any number of items.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";
Blockly.Msg.TEXT_LENGTH_TITLE = "length of %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Returns the number of letters (including spaces) in the provided text.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";
Blockly.Msg.TEXT_PRINT_TITLE = "print %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Print the specified text, number or other value.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Prompt for user for a number.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Prompt for user for some text.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "prompt for number with message";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "prompt for text with message";
Blockly.Msg.TEXT_REPLACE_HELPURL = "https://github.com/google/blockly/wiki/Text#replacing-substrings";
Blockly.Msg.TEXT_REPLACE_MESSAGE0 = "replace %1 with %2 in %3";
Blockly.Msg.TEXT_REPLACE_TOOLTIP = "Replace all occurances of some text within some other text.";
Blockly.Msg.TEXT_REVERSE_HELPURL = "https://github.com/google/blockly/wiki/Text#reversing-text";
Blockly.Msg.TEXT_REVERSE_MESSAGE0 = "reverse %1";
Blockly.Msg.TEXT_REVERSE_TOOLTIP = "Reverses the order of the characters in the text.";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "A letter, word, or line of text.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "trim spaces from both sides of";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "trim spaces from left side of";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "trim spaces from right side of";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Return a copy of the text with spaces removed from one or both ends.";
Blockly.Msg.TODAY = "Today";
Blockly.Msg.UNDO = "Undo";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "item";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Create 'set %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Returns the value of this variable.";
Blockly.Msg.VARIABLES_SET = "set %1 to %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Create 'get %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Sets this variable to be equal to the input.";
Blockly.Msg.VARIABLE_ALREADY_EXISTS = "A variable named '%1' already exists.";
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

Blockly.Msg.THREAD_TITLE = "PLC Simulate Thread";
Blockly.Msg.THREAD_DELAY_TITLE = "Delay %1 ms";
Blockly.Msg.THREAD_ALARM_TITLE = "Set PLC alarm";
Blockly.Msg.THREAD_SET_TIMER_TITLE = "Timer %1 count %2 ms";
Blockly.Msg.THREAD_RST_TIMER_TITLE = "Stop Timer";
Blockly.Msg.THREAD_GET_COIL_TITLE = "M";//Get
Blockly.Msg.THREAD_GET_D_TITLE = "Get D";
Blockly.Msg.MOTION_MOVEPTP_AVOID="MOVEPTPA To";
Blockly.Msg.MOTION_MOVEL_AVOID_LIST="Avoid list";
Blockly.Msg.MOTION_MODEL_ABSOLUTE ="Absolute mode";
Blockly.Msg.MOTION_TITLE_CREATEWITH = "Avoid point";
Blockly.Msg.MOTION_CREATE_ITEM_TOOLTIP = "Add point to";
Blockly.Msg.MOTION_CREATE_TITLE_JOIN = "Add";
Blockly.Msg.MOTION_CREATE_TOOLTIP = "Add, remove, or reorder sections to reconfigure this list block";
Blockly.Msg.MOTION_CREATE_ITEM_TITLE_ITEM_COND = "Cond";
Blockly.Msg.MOTION_CREATE_ITEM_IO_ITEM_COND = "IO Output";
Blockly.Msg.MOTION_CREATE_ITEM_OFFSET_ITEM_COND = "Offset";
Blockly.Msg.MOTION_CREATE_ITEM_TITLE_ITEM = "P";
Blockly.Msg.MOTION_CREATE_ITEM_TITLE_ITEM_ERR = "Err e";
Blockly.Msg.MOTION_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.MOTION_TEXT_TOOLTIP = "A letter, word, or line of text";
Blockly.Msg.MOTION_CREATE_ITEM_OFFSET_ITEM_COND = "Offset";

////
Blockly.Msg.MOTION_SPEED = "Speed";
Blockly.Msg.MOTION_OFFSET_ORIGIN = "Offset origin";
Blockly.Msg.MOTION_AXIS_NUM = "Axis-num";
Blockly.Msg.MOTION_DISTANCE = "Distance";
Blockly.Msg.MOTION_DISPLACEMENT_RATIO = "Displacement ratio r";
Blockly.Msg.MOTION_JOINT_MOVEMENT ="Joint movement";
Blockly.Msg.MOTION_JOG_BEGIN ="JOG-begin";
Blockly.Msg.MOTION_JOG_STOP ="JOG-stop";
Blockly.Msg.MOTION_MODE_RETURN_ZERO ="Return-zero mode";
Blockly.Msg.MOTION_MOVE_G51="Free Arch-shaped";
Blockly.Msg.MOTION_MOVE_G5="Line Arch-shaped";
Blockly.Msg.MOTION_MOVE_G16="Dynamic grasping";
Blockly.Msg.MOTION_MOVE_G1="Linear positioning";
Blockly.Msg.MOTION_MOVE_G0="Independent positioning";
Blockly.Msg.MOTION_MOVE_ZERO="Joint-to-zero Axis-Num %1 High speed %2 Low speed %3 Positive num %4 Negative num %5 Origin num %6 Z num %7";

Blockly.Msg.MOTION_POINT_INDEX="P";
Blockly.Msg.MOTION_CATCHUP_INDEX="Collar N";

Blockly.Msg.MOTION_EXEPLACE="Place To";
Blockly.Msg.MOTION_MOVEPTP="MOVEPTP To";
Blockly.Msg.MOTION_MOVEPTPL="MOVEPTPL To";
Blockly.Msg.MOTION_MOVEZTP="MOVEZTP To";
Blockly.Msg.MOTION_MOVERTP="MOVERTP To";
Blockly.Msg.MOTION_MOVEDG="MOVEDG To";
Blockly.Msg.MOTION_HEIGHTAVOID="HeightAvoid";
Blockly.Msg.MOTION_RADIUS="Radius";
Blockly.Msg.MOTION_DIR="Through";
Blockly.Msg.MOTION_MAXSPEED="MaxSpeed";
Blockly.Msg.MOTION_ENDSPEED="EndSpeed";
Blockly.Msg.MOTION_POS_ADJUST="PosAdjust";
Blockly.Msg.MOTION_ADJUST_Y="Yes";
Blockly.Msg.MOTION_ADJUST_N="No";
Blockly.Msg.MOTION_MOVEL="MOVEL To";
Blockly.Msg.MOTION_GET_CURRENT_AXISPOS="Get Current AxisPos";

Blockly.Msg.MOTION_MOVECIRCLE_NEGATIVA="Anticlockwise circle";
Blockly.Msg.MOTION_MOVECIRCLE_POSTIVE="Clockwise circle";
Blockly.Msg.MOTION_MOVECIRCLE_TARGET_POINT = 'End P';
Blockly.Msg.MOTION_MOVECIRCLE_TEMPLE_POINT = 'Mid P';
Blockly.Msg.MOTION_MOVECIRCLE_RADIUS =       'Radius';
Blockly.Msg.MOTION_MOVECIRCLE_ANGLERANGE =   'Arc angle';

Blockly.Msg.MOTION_GET_AXISPOS_VARIANTNAME="=";
Blockly.Msg.MOTION_GET_AXISPOS_POINTSAVETO="P";

Blockly.Msg.MOTION_GET_AXISPOS_POINTNAME=" P";
Blockly.Msg.MOTION_GET_AXISPOS_SAVETO="=";
Blockly.Msg.MOTION_GET_AXISPOS_X="X";
Blockly.Msg.MOTION_GET_AXISPOS_Y="Y";
Blockly.Msg.MOTION_GET_AXISPOS_Z="Z";
Blockly.Msg.MOTION_GET_AXISPOS_W="C";
Blockly.Msg.MOTION_GET_AXISPOS_U1="Axis-1 angle";
Blockly.Msg.MOTION_GET_AXISPOS_U2="Axis-2 angle";
Blockly.Msg.MOTION_GET_AXISPOS_U3="Axis-3 angle";
Blockly.Msg.MOTION_GET_AXISPOS_U4="Axis-4 angle";

Blockly.Msg.MOTION_GET_CURRENT_JOINTANGLE="Get Current JointAngle";
Blockly.Msg.MOTION_POS_JOINTANGLE="JointAngle";
Blockly.Msg.MOTION_POS_AXISPOS="AxisPos";
Blockly.Msg.MOTION_GET_POINT="Get Point";
Blockly.Msg.MOTION_SET_POINT="Set Point";
Blockly.Msg.MOTION_GET_IO_INPUT_STATUS="Get IO_Input Status";
Blockly.Msg.MOTION_GET_IO_OUTPUT_STATUS="Get IO_Output Status";
Blockly.Msg.MOTION_SET_IO_OUTPUT="Set IO_Output";
Blockly.Msg.MOTION_BUFFER_IO_OUTPUT="Buffer IO_Output";
Blockly.Msg.MOTION_SET_OUTPUT="Set Output";

Blockly.Msg.MOTION_RATIO_OUTPUT="dis ratio";
Blockly.Msg.MOTION_IO_OUTPUT_STATUS="Status";
Blockly.Msg.MOTION_SET_COMPORT="Set ComPort";
Blockly.Msg.MOTION_COMPORT="ComPort";
Blockly.Msg.MOTION_BAUDRATE="BaudRate";
Blockly.Msg.MOTION_DATABIT="DataBit";
Blockly.Msg.MOTION_STOPBIT="StopBit";
Blockly.Msg.MOTION_PARITYBIT="ParityBit";
Blockly.Msg.MOTION_PARITYBIT_EVEN="Even";
Blockly.Msg.MOTION_PARITYBIT_ODD="Odd";
Blockly.Msg.MOTION_PARITYBIT_NONE="None";
Blockly.Msg.MOTION_GET_REGISTERDATA="Get RegisterData";
Blockly.Msg.MOTION_GET_COILSTATUS="Get CoilStatus";
Blockly.Msg.MOTION_SET_REGISTERDATA="Set RegisterData";
Blockly.Msg.MOTION_REGISTERVALUE="Value";
Blockly.Msg.MOTION_SET_COIL="Set Coil";
Blockly.Msg.MOTION_COILSTATUS="Status";
Blockly.Msg.MOTION_DELAY="Delay";
Blockly.Msg.MOTION_MILLISECOND_UNIT="ms";
Blockly.Msg.MOTION_SECOND_UNIT="s";
Blockly.Msg.MOTION_SAVETO="Save to";

Blockly.Msg.MOTION_MOVE_OFFSET_X="OffSetX";
Blockly.Msg.MOTION_MOVE_OFFSET_Y="OffSetY";
Blockly.Msg.MOTION_MOVE_OFFSET_Z="OffSetZ";
Blockly.Msg.MOTION_MOVE_OFFSET_W="OffSetW";
Blockly.Msg.MOTION_MOVE_OFFSET_I="OffSetI";
Blockly.Msg.MOTION_MOVE_OFFSET_J="OffSetJ";
Blockly.Msg.MOTION_MOVE_OFFSET_θ="OffSetθ";

Blockly.Msg.MOTION_CENTER_OFFSET_X="OffSetX";
Blockly.Msg.MOTION_CENTER_OFFSET_Y="OffSetY";
Blockly.Msg.MOTION_CENTER_OFFSET_C="Angle";

Blockly.Msg.MOTION_MOVEPTP_DIR="MOVEPTP Dir";
Blockly.Msg.MOTION_MOVEPTP_DIR_START="Start Point";
Blockly.Msg.MOTION_MOVEPTP_DIR_DIR="Direction Point";
Blockly.Msg.MOTION_MOVEPTP_DIR_OFFSET="OffSet";

Blockly.Msg.MOTION_MOVE_COORDINATE="MOVE Coordinate";
Blockly.Msg.MOTION_MOVE_COORDINATE_START="Start Point";
Blockly.Msg.MOTION_MOVE_COORDINATE_XDIR="Row Point";
Blockly.Msg.MOTION_MOVE_COORDINATE_YDIR="Column Point";
Blockly.Msg.MOTION_MOVE_COORDINATE_XSTEP="Row Step";
Blockly.Msg.MOTION_MOVE_COORDINATE_YSTEP="Column Step";
Blockly.Msg.MOTION_MOVE_COORDINATE_XINDEX="Row Num";
Blockly.Msg.MOTION_MOVE_COORDINATE_YINDEX="Column Num";

Blockly.Msg.MOTION_ELEMENT_SET="Pos";
Blockly.Msg.MOTION_ELEMENT_RST="Reset";
Blockly.Msg.MOTION_ELEMENT_READ="Save";
Blockly.Msg.MOTION_ELEMENT_TO="To";
Blockly.Msg.MOTION_ELEMENT_WRITE="Modify";
Blockly.Msg.MOTION_ELEMENT_AS="As";

Blockly.Msg.MOTION_ELEMENT_TYPE_BIT="Switch";
Blockly.Msg.MOTION_ELEMENT_TYPE_DATA="Data";
Blockly.Msg.MOTION_ELEMENT_TYPE_V="V";
Blockly.Msg.MOTION_ELEMENT_TYPE_I="I";
Blockly.Msg.MOTION_ELEMENT_TYPE_J="J";
Blockly.Msg.MOTION_ELEMENT_TYPE_K="K";
Blockly.Msg.MOTION_ELEMENT_TYPE_W="W";

Blockly.Msg.MOTION_ELEMENT_TYPE_UP="↑";
Blockly.Msg.MOTION_ELEMENT_TYPE_DOWN="↓";
Blockly.Msg.MOTION_ELEMENT_TYPE_OFF="!";

Blockly.Msg.MOTION_ELEMENT_TYPE_X="X";
Blockly.Msg.MOTION_ELEMENT_TYPE_XUP="↑X";
Blockly.Msg.MOTION_ELEMENT_TYPE_XDOWN="↓X";
Blockly.Msg.MOTION_ELEMENT_TYPE_XOFF="!X";
Blockly.Msg.MOTION_ELEMENT_TYPE_Y="Y";
Blockly.Msg.MOTION_ELEMENT_TYPE_YUP="↑Y";
Blockly.Msg.MOTION_ELEMENT_TYPE_YDOWN="↓Y";
Blockly.Msg.MOTION_ELEMENT_TYPE_YOFF="!Y";
Blockly.Msg.MOTION_ELEMENT_TYPE_M="M";
Blockly.Msg.MOTION_ELEMENT_TYPE_MUP="↑M";
Blockly.Msg.MOTION_ELEMENT_TYPE_MDOWN="↓M";
Blockly.Msg.MOTION_ELEMENT_TYPE_MOFF="!M";
Blockly.Msg.MOTION_ELEMENT_TYPE_S="S";
Blockly.Msg.MOTION_ELEMENT_TYPE_SUP="↑S";
Blockly.Msg.MOTION_ELEMENT_TYPE_SDOWN="↓S";
Blockly.Msg.MOTION_ELEMENT_TYPE_SOFF="!S";
Blockly.Msg.MOTION_ELEMENT_TYPE_T="T";
Blockly.Msg.MOTION_ELEMENT_TYPE_TUP="↑T";
Blockly.Msg.MOTION_ELEMENT_TYPE_TDOWN="↓T";
Blockly.Msg.MOTION_ELEMENT_TYPE_TOFF="!T";
Blockly.Msg.MOTION_ELEMENT_TYPE_C="C";
Blockly.Msg.MOTION_ELEMENT_TYPE_CUP="↑C";
Blockly.Msg.MOTION_ELEMENT_TYPE_CDOWN="↓C";
Blockly.Msg.MOTION_ELEMENT_TYPE_COFF="!C";


Blockly.Msg.MOTION_ELEMENT_TYPE_D="D";
Blockly.Msg.MOTION_ELEMENT_TYPE_CONST="#";

Blockly.Msg.MOTION_COILSTATUS_SET="Pos";
Blockly.Msg.MOTION_COILSTATUS_RST="Reset";

Blockly.Msg.MOTION_IO_OUTPUT_STATUS_SET="Output";
Blockly.Msg.MOTION_IO_OUTPUT_STATUS_RST="Clean";


Blockly.Msg.MOTION_ERROR_SPEEDERROR = "Please check if the maximum and minimum speed settings are correct. The maximum speed is greater than 0 and the minimum speed is greater than or equal to 0";
Blockly.Msg.MOTION_ERROR_POINTINDEXERROR = "Please check if the coordinate point number is correct, only integers greater than or equal to 0 can be filled in";
Blockly.Msg.MOTION_ERROR_POINT_NOT_EXIST = "P does not exist in the saved point library";
Blockly.Msg.CONTROL_ERROR_LOGICERROR = "This module cannot be used as a standalone statement, please connect to other statements for use!";
Blockly.Msg.MATH_ERROR_NUMBERERROR = "This module cannot be used as a standalone statement, please connect to other statements for use!";
Blockly.Msg.MOTION_ERROR_READERROR = "This module cannot be used as a standalone statement, please connect to other statements for use!";
Blockly.Msg.CAMERA_ERROR_CAMERAINDEXERROR="Please check if the camera number is correct, only integers greater than or equal to 0 can be filled in";
Blockly.Msg.CAMERA_ERROR_OBJECTINDEXERROR="Please check if the product number is correct, only integers greater than or equal to 0 can be filled in";
Blockly.Msg.CAMERA_ERROR_OBJECTNUMBERERROR="Please check if the number of products is correct, only integers greater than or equal to 0 can be filled in";

Blockly.Msg.MOTION_STARTMOVE = "Begin moving";
Blockly.Msg.MOTION_WAITROBOT = "Wait for the action to complete";

Blockly.Msg.PROJECT_NAME = "ProjectName";
Blockly.Msg.EXECUTE_RESULT="Execute Result";

// Blockly.Msg.MOTION_ELEMENT_TYPE_eI="EtherCATIn";
// Blockly.Msg.MOTION_ELEMENT_EtherCAT="EtherCATOut";
// Blockly.Msg.MOTION_ELEMENT_TYPE_I="In";
// Blockly.Msg.MOTION_ELEMENT_TYPE_O="Out";
// Blockly.Msg.MOTION_ELEMENT_TYPE_X="X";
// Blockly.Msg.MOTION_ELEMENT_TYPE_Y="Y";
// Blockly.Msg.MOTION_ELEMENT_TYPE_M="M";
// Blockly.Msg.MOTION_ELEMENT_TYPE_S="S";
// Blockly.Msg.MOTION_ELEMENT_TYPE_T="T";
// Blockly.Msg.MOTION_ELEMENT_TYPE_C="C";

Blockly.Msg.MOTION_COILSTATUS_SET="SET";
Blockly.Msg.MOTION_COILSTATUS_RST="RST";
Blockly.Msg.MOTION_STARTMOVE = "Robot Start Move";
Blockly.Msg.MOTION_WAITROBOT = "WaitRobot MotionComplete";

Blockly.Msg.MOTION_IO_OUTPUT_STATUS_SET="SET";
Blockly.Msg.MOTION_IO_OUTPUT_STATUS_RST="RST";

Blockly.Msg.CAMERA_GRABIMAGE = "Camera Grab Image";
Blockly.Msg.CAMERA_GET="Get";
Blockly.Msg.CAMERA_POS_AXISPOS = "Camera AxisPos";
Blockly.Msg.CAMERA_COORDINATE="Coordinate";

Blockly.Msg.CAMERA_CAMERAINDEX="Camera Index";
Blockly.Msg.CAMERA_OBJECTINDEX="Object Index";
Blockly.Msg.CAMERA_OBJECTNUMBER="Object Number";
Blockly.Msg.CAMERA_OFFSETINDEX="OffSet Index";
Blockly.Msg.CAMERA_GRABRESULT="Grab Result";
Blockly.Msg.CAMERA_CALRESULT="Calculate Result";
Blockly.Msg.CAMERA_SAVE_TO_POINT="Calculate Result Save To Point";

Blockly.Msg.CAMERA="camera";
Blockly.Msg.CAMERA_PLACE="place";
Blockly.Msg.CAMERA_FIXED_POS="fixed pos";
Blockly.Msg.CAMERA_IMAGE_POS="image pos";

Blockly.Msg.MOTION_PLC_TYPE="PLC Type";
Blockly.Msg.MOTION_PLC_TYPE_FX="FXSeries";
Blockly.Msg.MOTION_PLC_TYPE_XJ="XunJie";
Blockly.Msg.MOTION_PLC_TYPE_DEFAULT ="Default";


////
Blockly.Msg.MATH_HUE = "100";//#c5c6caS
Blockly.Msg.LOOPS_HUE = "100";//120
Blockly.Msg.LISTS_HUE = "100";//260
Blockly.Msg.LOGIC_HUE = "100";//210
Blockly.Msg.VARIABLES_HUE = "100";//330
Blockly.Msg.TEXTS_HUE = "100";//160
Blockly.Msg.PROCEDURES_HUE = "100";//290
Blockly.Msg.COLOUR_HUE = "100";//20

//定义toolbox 按下时的颜色
// Blockly.Msg.FOCUS_RETURN_RGB = Blockly.CustomConfig.FOCUS_RETURN_RGB;
Blockly.Msg.FOCUS_MOTION_RGB = Blockly.CustomConfig.FOCUS_MOTION_RGB;
Blockly.Msg.FOCUS_CONTROL_RGB = Blockly.CustomConfig.FOCUS_CONTROL_RGB;//#c5c6ca
Blockly.Msg.FOCUS_EVENT_RGB = Blockly.CustomConfig.FOCUS_EVENT_RGB;//#c5c6ca
Blockly.Msg.FOCUS_MATH_RGB = Blockly.CustomConfig.FOCUS_MATH_RGB;//#c5c6ca
Blockly.Msg.FOCUS_MATH_NUM_RGB = Blockly.CustomConfig.FOCUS_MATH_NUM_RGB;//#c5c6ca
Blockly.Msg.FOCUS_VARIABLES_RGB = Blockly.CustomConfig.FOCUS_VARIABLES_RGB;//#c5c6ca
Blockly.Msg.FOCUS_CAMERA_RGB = Blockly.CustomConfig.FOCUS_CAMERA_RGB;//#c5c6ca
Blockly.Msg.FOCUS_PROCEDURES_RGB = Blockly.CustomConfig.FOCUS_PROCEDURES_RGB;//#c5c6ca
Blockly.Msg.FOCUS_MATH_NOTE_RGB = Blockly.CustomConfig.BLOCK_MATH_NOTE_RGB;

//定义  不同block类型的颜色
Blockly.Msg.BLOCK_MOTION_RGB = Blockly.CustomConfig.BLOCK_MOTION_RGB;
Blockly.Msg.BLOCK_CONTROL_RGB = Blockly.CustomConfig.BLOCK_CONTROL_RGB;
Blockly.Msg.BLOCK_EVENT_RGB = Blockly.CustomConfig.BLOCK_EVENT_RGB;
Blockly.Msg.BLOCK_MATH_RGB = Blockly.CustomConfig.BLOCK_MATH_RGB;
Blockly.Msg.BLOCK_MATH_NOTE_RGB = Blockly.CustomConfig.BLOCK_MATH_NOTE_RGB;
Blockly.Msg.BLOCK_MATH_NUM_RGB = Blockly.CustomConfig.BLOCK_MATH_NUM_RGB;
Blockly.Msg.BLOCK_VARIABLES_RGB = Blockly.CustomConfig.BLOCK_VARIABLES_RGB;
Blockly.Msg.BLOCK_CAMERA_RGB = Blockly.CustomConfig.BLOCK_CAMERA_RGB;
Blockly.Msg.BLOCK_PROCEDURES_RGB = Blockly.CustomConfig.BLOCK_PROCEDURES_RGB;

/**
 * 添1加
 *
 *   */
Blockly.Msg.MOTION_CREATE_ITEM_TITLE_ITEM_POS = "Pos";


Blockly.Msg.MOTION_MOVE_ARC_CLOCKWISE_G2 = "Along arc";
Blockly.Msg.MOTION_MOVE_ARC_ANTICCLOCKWISE_G3 = "Inverse arc";
Blockly.Msg.MOTION_MOVE_ARC_END_POINT="EndPoint";
Blockly.Msg.MOTION_MOVE_ARC_MID_POINT="MidPoint";


/**
7.12添加电子齿轮
*/
Blockly.Msg.MOTION_MOVE_ELE_GEAR="Electronic Gearing";
Blockly.Msg.MOTION_MOVE_ELE_GEAR_DRIVING="Driving-axis";
Blockly.Msg.MOTION_MOVE_ELE_GEAR_FOLLOWER="Following-axis";
Blockly.Msg.MOTION_MOVE_ELE_GEAR_NUMERATOR="Numerator";
Blockly.Msg.MOTION_MOVE_ELE_GEAR_DENOMINATOR="Denominator";

Blockly.Msg.MAIN_TOOL_LOGIC="Logic";
Blockly.Msg.MAIN_TOOL_VARIABLE="Variable";
Blockly.Msg.MAIN_TOOL_MOVE="Move";
Blockly.Msg.MAIN_TOOL_CUSTOM="Custom";